### ISSUE TITLE
Clarify license in file headers and repo root

### ISSUE THREAD

**Issue by MetalJulia** [greys-bots/alex#10]
Currently the repository has no LICENSE file or similar, which would indicate this software is "all rights reserved." The package.json, however, lists the license as ISC. Could you please add license information to the repository to clear this confusion up? I suggest following the [REUSE standard.](https://reuse.software/)

**Comment by selenated** [comment]
We'd prefer to avoid anything that requires individual licensing per file, if only for effort's sake 😅

That said, we do need to take another look at the licenses used in our repos, so we'll try to get that done tonight and get an official license file in here

**Comment by selenated** [comment]
Okee doke, we've added the AGPL to the repo and clarified it in `package.json`. Thanks for the reminder to do that :3
